spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: serviceProduct
          uri: lb://MICROSERVICE-PRODUCT
          predicates:
          - After=2017-01-20T17:42:47.789-07:00[America/Denver]

server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/









